Repository introlab/rendezvous, pull requests merged in 2019-11, with the labels that each got.

#105 Rdv 334 odas process
  steno/src/model/network/local_socket_server.cpp
  steno/src/model/settings/settings_constants.h
  steno/src/model/stream/audio/odas/odas_client.cpp
  steno/src/model/stream/audio/odas/odas_client.h
  steno/src/model/stream/i_stream.h
  steno/src/model/stream/stream.cpp
  steno/src/model/stream/stream.h
  steno/src/model/utils/observer/i_observer.h
  steno/src/model/utils/observer/i_subject.h
  steno/src/view/views/local_conference_view.cpp
  steno/src/view/views/online_conference_view.cpp
  steno/src/view/views/online_conference_view.h
  steno/steno.pro
Labels: enhancement

#110 Rdv 237 Stream buttons are linked
  scripts/format.sh
  steno/src/main.cpp
  steno/src/model/recorder/i_recorder.h
  steno/src/model/recorder/recorder.cpp
  steno/src/model/recorder/recorder.h
  steno/src/model/stream/audio/audio_config.h
  steno/src/model/stream/audio/odas/odas_audio_source.cpp
  steno/src/model/stream/audio/odas/odas_audio_source.h
  steno/src/model/stream/audio/odas/odas_client.cpp
  steno/src/model/stream/audio/odas/odas_client.h
  steno/src/model/stream/i_stream.h
  steno/src/model/stream/media_thread.cpp
  steno/src/model/stream/stream.cpp
  steno/src/model/stream/stream.h
  steno/src/model/utils/observer/i_observer.h
  steno/src/model/utils/observer/i_subject.h
  steno/src/view/gui/local_conference_view.ui
  steno/src/view/gui/online_conference_view.ui
  steno/src/view/mainwindow.cpp
  steno/src/view/mainwindow.h
  steno/src/view/views/local_conference_view.cpp
  steno/src/view/views/local_conference_view.h
  steno/src/view/views/media_player_view.cpp
  steno/src/view/views/media_player_view.h
  steno/src/view/views/online_conference_view.cpp
  steno/src/view/views/online_conference_view.h
  steno/src/view/views/settings_view.cpp
  steno/src/view/views/settings_view.h
Labels: enhancement

#111 virtual camera creation automation
  JetsonREADME.md
  scripts/StenoCam/automation.sh
  scripts/StenoCam/stenocam-creation.sh
  scripts/StenoCam/stenocam.service
Labels: enhancement

#113 Rdv 330 transcription api
  .gitignore
  transcription_api/app.js
  transcription_api/config/.envTemplate
  transcription_api/config/production/.env
  transcription_api/env.js
  transcription_api/package-lock.json
  transcription_api/package.json
  transcription_api/public/index.html
  transcription_api/readme.md
  transcription_api/routes.js
  transcription_api/src/controllers/index.js
  transcription_api/src/core/g_storage.js
  transcription_api/src/utils/HttpError.js
  transcription_api/ssl/req.cnf
Labels: dependencies, enhancement

#132 pass travis to ubuntu 18
  .travis.yml
Labels: dependencies

#131 RDV-368 Transcription request to transcription_api
  steno/resources/test-transcription.wav
  steno/src/main.cpp
  steno/src/model/config/config.cpp
  steno/src/model/transcription/transcription.cpp
  steno/src/model/transcription/transcription.h
  steno/src/model/transcription/transcription_constants.h
  steno/src/view/components/top_bar.cpp
  steno/src/view/components/top_bar.h
  steno/src/view/mainwindow.cpp
  steno/src/view/mainwindow.h
  steno/src/view/views/settings_view.cpp
  steno/steno.pro
  transcription_api/src/controllers/transcription.js
Labels: enhancement

#135 push default image when the stream is stopped
  steno/src/model/stream/stream.cpp
  steno/src/model/stream/stream.h
  steno/src/model/stream/video/output/default_virtual_camera_output.cpp
Labels: bug
